scaling
delgod/mongodb-k8s-operator pull request #1
Opened 2022-04-08 20:14 UTC by delgod

2022-04-09 09:03 UTC, jnsgruk commented
@hpidcock where are we on the pebble finaliser work that will enable us to handle stop/remove consistently on k8s?

2022-04-11 08:13 UTC, MiaAltieri requested changes
Hi Mykola! Looks great! I really like a lot of your implementation here, great work! Just some notes:

1. Docstrings, aggressive wrappings, etc, might want to lint before pushing (or better add tox checks to GitHub actions)
2. Functions need comments 
3. Missing integration and unit tests are these going to be in a future PR

2022-04-11 08:13 UTC, MiaAltieri commented on src/charm.py
>          if "replset_initialized" not in self._app_data:
To avoid heavy nesting I'd recommend 
```suggestion
        # skip initialisation if already initialised 
        if "replset_initialized" in self._app_data:
               return 
```

2022-04-11 08:13 UTC, MiaAltieri commented on src/charm.py
>          if "replset_initialized" not in self._app_data:
this is a super nit, but Canonical uses British English instead of American english which means initialized ---> initialised (As an American I mess this up all the time 😅 )

2022-04-11 08:13 UTC, MiaAltieri commented on src/charm.py
> +    def _on_start(self, event) -> None:
This function could use some comments

2022-04-11 08:13 UTC, MiaAltieri commented on lib/charms/mongodb_libs/v0/mongodb.py
>      In this class we create connection object to MongoDB.
nit: `direct` --> `standalone`

2022-04-11 08:13 UTC, MiaAltieri commented on src/charm.py
> +                if replset_members != self._mongodb_config.hosts:  # compare sets
avoid heavy nesting:
``
```suggestion
                if replset_members == self._mongodb_config.hosts:  
                         return
```

2022-04-11 08:13 UTC, MiaAltieri commented on src/charm.py
> +    def _reconfigure(self, event) -> None:
function needs comments

2022-04-11 08:13 UTC, MiaAltieri commented on tests/integration/test_charm.py
> +    assert response["ok"] == 1
Missing tests for add unit, remove unit, accurate config, only one primary, etc

2022-04-11 08:13 UTC, MiaAltieri commented on tests/unit/test_charm.py
>      harness.add_oci_resource("mongodb-image", mongo_resource)
missing unit tests

2022-04-11 08:31 UTC, MiaAltieri requested changes
One last thing

2022-04-11 08:31 UTC, MiaAltieri commented on src/charm.py
> +    def _reconfigure(self, event) -> None:
With `relation-departed` we need to be VERY careful here. Say you have this scenario:
```
A*
B +
C
```
`*`-leader
`+`-primary

and you `del B` but unit `A*`  is VERY busy and so unit `B` goes through all of its hooks i.e. `storage-detached`, `relation-departed`, `stop`, and `remove` _all before_ `A*` executes `reconfigure`. Then you have a situation where `A*` tries to step `B+` down as the primary but we no longer have a connection to `B+` and so stepping down and reconfiguring will not be possible until `mongod` re-elects a new primary thus leading to some downtime.

Similarly, we need to be mindful of re-electing and reconfiguring before unit `B+` finishes its `StorageDetachingHook`,  since "Callback methods bound to this event allow the charm to run code before storage is removed."  so after `StorageDetaching` for `B` we will no longer have access to its storage.

There is a pattern I am developing for this in my next PR, lets sync to discuss

2022-04-11 10:56 UTC, jnsgruk commented on lib/charms/mongodb_libs/v0/mongodb.py
> +            hostname == str(member["name"]).split(":")[0]
Feels like I've seen `str(member["name"]).split(":")[0]` a few times in this PR -- I think I'd probably break it into a private helper method and wrap some more logic to catch any issues, perhaps something like;

```python
def _hostname_from_replset_member(member: dict) -> str:
  splits = str(member.get("name", "")).split(":")
  if splits:
    return splits[0]
  else:
    # can't decide best path here, but either:
    return ""
    # or perhaps
    # raise ValueError("member name invalid")
```

2022-04-11 10:59 UTC, jnsgruk commented on metadata.yaml
> +    location: db
It shouldn't really matter, but providing an absolute path is probably a better plan.

2022-04-11 11:01 UTC, jnsgruk commented
Overall this is looking nice! Thanks Mykola.

2022-04-11 13:12 UTC, delgod commented on lib/charms/mongodb_libs/v0/mongodb.py
> +            for attempt in Retrying(stop=stop_after_delay(60), wait=wait_fixed(3)):
Just 1 second longer than the two-second connection timeout. Want to be fast.
In most cases, It takes up to 10 seconds from executing mongod till open port.

2022-04-11 14:11 UTC, delgod commented on src/charm.py
> +    def _reconfigure(self, event) -> None:
Can you suggest an improvement?
It is bad practice to describe what code is obviously doing in a comment. A good practice is to have an explanation of why code is doing something or what non-obvious code is doing.
Otherwise, comments only blur attention from essential things.

2022-04-11 15:39 UTC, MiaAltieri commented on src/charm.py
> +    def _reconfigure(self, event) -> None:
Hi! Are you referring to the part where you say "it is impossible to block unit departure in Kubernetes"?

2022-04-11 15:47 UTC, MiaAltieri commented on src/charm.py
> +    def _reconfigure(self, event) -> None:
Hi! I think I might be confused by your PR description 😅 , you say:

"**Right now, it is impossible to block unit departure in Kubernetes.** So we update the replicate set config afterward.
_As a result, scaling down works only if we remove less than half of the current members_. e.g., 5->3 works, 2->1 doesn't work."

Just to be sure that we are on the same page do you mean that:
1. It is impossible to block unit departure but you get around it by removing half of the current members? 
OR
2. By saying "Right now, it is impossible to block unit departure in Kubernetes" are you saying that you acknowledge this edge case?

2022-04-12 07:32 UTC, MiaAltieri commented on lib/charms/mongodb_libs/v0/mongodb.py
>      In this class we create connection object to MongoDB.
Ah I think it is confusing because in the docstring the terms are a little mixed (ie you refer to direct as a "standalone connection" 

 See [line 77](https://github.com/delgod/mongodb-k8s-operator/blob/188c676daf57c630059dc72ff4890f2f361eb3cc/lib/charms/mongodb_libs/v0/mongodb.py#L77) `direct: force standalone connection, needed for replSet init`

Are you sure calling it `standalone_connection` wouldn't make more sense here as to match the argument description?

2022-04-12 07:35 UTC, MiaAltieri commented on lib/charms/mongodb_libs/v0/mongodb.py
> +        """Checking if passed member is primary"""
I agree for the variable `hostname`, but `rs_status` isn't an obvious variable here and should be described

2022-04-12 07:37 UTC, MiaAltieri commented on lib/charms/mongodb_libs/v0/mongodb.py
> +        performance degradation.
I don't think `rs_status` is an obvious variable name, I agree for `hostname` but `rs_status` is only known by some people within the MongoDB community and we want this code to be readable for everyone in the MongoDB community and for people outside of MongoDB so that new Devs can easily contribute (IMO)

2022-04-12 07:56 UTC, delgod commented on lib/charms/mongodb_libs/v0/mongodb.py
>      In this class we create connection object to MongoDB.
thanks!
I will fix `s/standalone/directConnection/` in [line 77](https://github.com/delgod/mongodb-k8s-operator/blob/188c676daf57c630059dc72ff4890f2f361eb3cc/lib/charms/mongodb_libs/v0/mongodb.py#L77)
right terminology (from MongoDB point of view) here is `directConnection` (not `standalone`)

2022-04-12 10:34 UTC, MiaAltieri commented on lib/charms/mongodb_libs/v0/mongodb.py
>  import logging
Assigned to me

2022-04-12 10:34 UTC, MiaAltieri commented on lib/charms/mongodb_libs/v0/mongodb.py
> +    def get_replset_members(self) -> Set[str]:
Assigned to me

2022-04-12 10:34 UTC, MiaAltieri commented on lib/charms/mongodb_libs/v0/mongodb.py
> +            str(member["name"]).split(":")[0] for member in rs_status["members"]
Assigned to Mykola

2022-04-12 10:35 UTC, MiaAltieri commented on lib/charms/mongodb_libs/v0/mongodb.py
> +        self.client.admin.command("replSetReconfig", rs_config["config"])
Assigned to me to write a comment with how error handling (in each function and header of the class docstring)
with ....
    try:
         thing
    catch e:
         thing

2022-04-12 10:36 UTC, MiaAltieri commented on lib/charms/mongodb_libs/v0/mongodb.py
> +            # it is fast, we will @retry(3 times with a 5sec timeout) before giving up
Assigned to Mykola

2022-04-12 10:36 UTC, MiaAltieri commented on lib/charms/mongodb_libs/v0/mongodb.py
> +        self.client.admin.command("replSetReconfig", rs_config["config"])
Assigned to me (see above)

2022-04-12 10:36 UTC, MiaAltieri commented on lib/charms/mongodb_libs/v0/mongodb.py
> +        """Checking if passed member is primary"""
Assigned to me

2022-04-12 10:37 UTC, MiaAltieri commented on lib/charms/mongodb_libs/v0/mongodb.py
> +            hostname == str(member["name"]).split(":")[0]
Assigned to Mykola

2022-04-12 10:37 UTC, MiaAltieri commented on lib/charms/mongodb_libs/v0/mongodb.py
> +        performance degradation.
Assigned to me

2022-04-12 10:37 UTC, MiaAltieri commented on lib/charms/mongodb_libs/v0/mongodb.py
> +    def _is_any_removing(rs_status: Dict) -> bool:
Assigned to me

2022-04-12 10:37 UTC, MiaAltieri commented on metadata.yaml
> +    location: db
Assigned to Mykola

2022-04-12 10:47 UTC, MiaAltieri commented on src/charm.py
>          if "replset_initialized" not in self._app_data:
Assigned to Mykola

2022-04-12 10:51 UTC, MiaAltieri commented on src/charm.py
>          if "replset_initialized" not in self._app_data:
Assigned to me

2022-04-12 10:56 UTC, MiaAltieri commented on lib/charms/mongodb_libs/v0/mongodb.py
>      In this class we create connection object to MongoDB.
Assigned to Mykola

2022-04-12 10:56 UTC, MiaAltieri commented on src/charm.py
> +                if replset_members != self._mongodb_config.hosts:  # compare sets
Assigned to Me

2022-04-12 10:57 UTC, MiaAltieri commented on tests/integration/test_charm.py
> +    assert response["ok"] == 1
Okay I will do this in a future PR to this Repo

2022-04-12 10:57 UTC, MiaAltieri commented on tests/unit/test_charm.py
>      harness.add_oci_resource("mongodb-image", mongo_resource)
Okay I will do this in a future PR to this Repo

2022-04-17 16:56 UTC, delgod commented on lib/charms/mongodb_libs/v0/mongodb.py
> +            str(member["name"]).split(":")[0] for member in rs_status["members"]
fixed in https://github.com/delgod/mongodb-k8s-operator/pull/1/commits/37a9a765a1abb8048348e8bc331a2400eb615a89

2022-04-17 16:57 UTC, delgod commented on lib/charms/mongodb_libs/v0/mongodb.py
> +            hostname == str(member["name"]).split(":")[0]
fixed in https://github.com/delgod/mongodb-k8s-operator/pull/1/commits/37a9a765a1abb8048348e8bc331a2400eb615a89

2022-04-17 16:57 UTC, delgod commented on metadata.yaml
> +    location: db
fixed in https://github.com/delgod/mongodb-k8s-operator/pull/1/commits/37a9a765a1abb8048348e8bc331a2400eb615a89

2022-04-17 16:57 UTC, delgod commented on src/charm.py
>          if "replset_initialized" not in self._app_data:
fixed in https://github.com/delgod/mongodb-k8s-operator/pull/1/commits/37a9a765a1abb8048348e8bc331a2400eb615a89

2022-04-17 17:00 UTC, delgod commented on lib/charms/mongodb_libs/v0/mongodb.py
> +            str(member["name"]).split(":")[0] for member in rs_status["members"]
fixed in docstring for `_hostname_from_hostport ` function in https://github.com/delgod/mongodb-k8s-operator/commit/37a9a765a1abb8048348e8bc331a2400eb615a89

2022-04-17 17:01 UTC, delgod commented on lib/charms/mongodb_libs/v0/mongodb.py
>      In this class we create connection object to MongoDB.
fixed in https://github.com/delgod/mongodb-k8s-operator/pull/1/commits/2af271c0fd4efc32d1d89558f46937eb2976a846

2022-04-17 17:02 UTC, delgod commented on lib/charms/mongodb_libs/v0/mongodb.py
> +            # it is fast, we will @retry(3 times with a 5sec timeout) before giving up
fixed in https://github.com/delgod/mongodb-k8s-operator/pull/1/commits/2af271c0fd4efc32d1d89558f46937eb2976a846

2022-04-19 19:28 UTC, jnsgruk approved these changes

2022-04-20 09:17 UTC, MiaAltieri approved these changes

2022-04-20 12:39 UTC, merged