Replication data consistency integration test
delgod/mongodb-k8s-operator pull request #17
Opened 2022-07-20 11:04 UTC by Mehdi-Bendriss

This PR contains:

- integration test, for testing the data consistency on the replica set, by writing on the primary, then reading data from the secondaries

2022-07-21 15:35 UTC, MiaAltieri requested changes

2022-07-21 15:35 UTC, MiaAltieri commented on src/charm.py
> +        return relation.data[self.app]
good eye on this, I'll need to update this in my charm as well :)

2022-07-21 15:35 UTC, MiaAltieri commented on src/charm.py
> +
good catch here aswell

2022-07-21 15:35 UTC, MiaAltieri commented on tests/integration/helpers.py
> +        unit_ids = UNIT_IDS
```suggestion
async def mongodb_uri(ops_test: OpsTest, unit_ids: List[int] = UNIT_IDS) -> str:
```

2022-07-21 15:35 UTC, MiaAltieri commented on tests/integration/helpers.py
> +def primary_host(rs_status_data) -> Optional[str]:
nit:
```suggestion
def primary_host(rs_status_data: Dict) -> Optional[str]:
```

2022-07-21 15:35 UTC, MiaAltieri commented on tests/integration/helpers.py
> +            assert db_doc[key] == val
If this code is testing something the asserts might be better for the test code in `test/integration/test_charm.py`

2022-07-21 15:35 UTC, MiaAltieri commented on tests/integration/helpers.py
> +
this is so much of a nit that I debated commenting or not, so do whatever you want here
```suggestion
    secondaries = []
    for member in rs_status_data["members"]:
        if member["stateStr"].upper() != "SECONDARY":
            continue

        unit_id = member["name"].split(".")[0].split("-")[-1]
        member_optime_date = datetime.strptime(member["optimeDate"], "%Y-%m-%dT%H:%M:%S.%fZ")
        host = await mongodb_uri(ops_test, [unit_id])
        delay_seconds = (primary_optime_date - member_optime_date).total_seconds()
        secondaries.append({"uri": host, "delay": math.fabs(delay_seconds)})

```

2022-07-21 15:35 UTC, MiaAltieri commented on tests/integration/helpers.py
> +async def secondary_mongo_uris_with_sync_delay(ops_test: OpsTest, rs_status_data):
add docstring

2022-07-21 15:35 UTC, MiaAltieri commented on tests/integration/test_charm.py
> +    await k8s_client.delete(Pod, name=replica_name)
neat :)

2022-07-21 15:35 UTC, MiaAltieri commented on tests/integration/test_charm.py
> +    time.sleep(24)
tenacity might be better here (unless like above you have a specific reason for choosing 24)

2022-07-21 15:35 UTC, MiaAltieri commented on tests/integration/test_charm.py
> +    # query the secondaries with the pymongo default behavior: majority
nit: quick explaination of "the pymongo default behavior: majority"

2022-07-21 15:35 UTC, MiaAltieri commented on tests/integration/test_charm.py
> +        time.sleep(secondary["delay"] + 2)  # probably useless, but attempting
definitely use tenacity here, see [this](https://github.com/canonical/mongodb-operator/blob/df379d065d78b43bd04e69ed1f6fde421761852d/lib/charms/mongodb_libs/v0/mongodb.py#L141-L147) as an example

2022-07-21 15:35 UTC, MiaAltieri commented on tests/integration/test_charm.py
> +    secondaries = await secondary_mongo_uris_with_sync_delay(ops_test, rs_status.data)
quick explaination why it is necessary to check with a delay

2022-07-21 15:35 UTC, MiaAltieri commented
Looking awesome @Mehdi-Bendriss really great work and thanks for the help on getting this up to speed :)

2022-07-22 08:51 UTC, Mehdi-Bendriss commented on tests/integration/helpers.py
> +        unit_ids = UNIT_IDS
So I think in this specific case it does not makes much of a difference as the pointed object remains the mutable `UNIT_IDS`, but setting mutable default arguments in python can be risky, so I try to avoid it altogether https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments

2022-07-22 13:39 UTC, Mehdi-Bendriss commented on tests/integration/helpers.py
> +            assert db_doc[key] == val
So I'm a bit torn about this one tbh, it's not really a test per-se that makes sense on its own, but rather a reusable helper that asserts certain things and gets called by actual integration tests

2022-07-22 15:28 UTC, Mehdi-Bendriss commented on tests/integration/test_charm.py
> +    time.sleep(24)
I added a comment, but it's really just a sleep, not a retry (24sec being an arbitrary number that worked well locally in a couple of tests, 12 sec being the median time for primary reelection, so I randomly chose a factor for this wait)

2022-07-25 11:31 UTC, MiaAltieri submitted a review, later dismissed

2022-07-25 17:04 UTC, delgod approved these changes

2022-07-26 07:32 UTC, MiaAltieri approved these changes

2022-07-26 07:39 UTC, merged