Refactoring preparations for relations
delgod/mongodb-k8s-operator pull request #2
Opened 2022-04-20 12:45 UTC by delgod

in this PR:
* `README.md` and `CONTRIBUTING.md`
* config option and relations are renamed.
* renamed fields inside internal config structure.
* peer relation and config properties made public for future usage in the next PR

2022-04-20 12:52 UTC, jnsgruk requested changes

2022-04-20 12:52 UTC, jnsgruk commented on CONTRIBUTING.md
> +
LXD isn't needed for the k8s charm :)

2022-04-20 12:52 UTC, jnsgruk commented on README.md
> +automatic recovery on failover. The solution includes scaling and other capabilities.
```suggestion
automatic recovery and failover. The solution includes scaling and other capabilities.
```

?

2022-04-20 12:52 UTC, jnsgruk commented on config.yaml
>      description: Delete database if relations are removed
```suggestion
    description: |
        When a relation is removed, auto-delete ensures that any relevant databases 
        associated with the relation are also removed
```

2022-04-20 15:39 UTC, MiaAltieri commented on src/charm.py
> +PEER = "database-peers"
Just curious what motivated this name change?

2022-04-20 15:40 UTC, MiaAltieri commented on metadata.yaml
> +    interface: mongodb-client
As of now the machine charm doesn't provide an interface

2022-04-20 16:18 UTC, jnsgruk commented on metadata.yaml
> +    interface: mongodb-client
The existing charm that bootstack maintained does :)

2022-04-21 08:09 UTC, delgod commented on README.md
> +automatic recovery on failover. The solution includes scaling and other capabilities.
wording can be better, automatic traffic switch needed on failover and automatic DB files recovery is needed during next start after HW fail.

2022-04-21 08:10 UTC, delgod commented on CONTRIBUTING.md
> +juju deploy ./mongodb_ubuntu-20.04-amd64.charm --resource mongodb-image=mongo:4.4 --num-units=1
I think the name is correct 
```
% charmcraft pack
Charms packed:
    mongodb_ubuntu-20.04-amd64.charm
```

2022-04-21 08:10 UTC, delgod commented on README.md
> +    juju deploy ./mongodb_ubuntu-20.04-amd64.charm --resource mongodb-image=mongo:4.4 --num-units=1
I think the name is correct 
```
% charmcraft pack
Charms packed:
    mongodb_ubuntu-20.04-amd64.charm
```

2022-04-21 08:11 UTC, delgod commented on config.yaml
>      description: Delete database if relations are removed
fixed in https://github.com/delgod/mongodb-k8s-operator/pull/2/commits/f1f3003da6928606039362b9be89055f5a2c77d2

2022-04-21 08:12 UTC, jnsgruk commented on README.md
> +    juju deploy ./mongodb_ubuntu-20.04-amd64.charm --resource mongodb-image=mongo:4.4 --num-units=1
Ah well in that case, the `metadata.yaml` is wrong ;-) The `metadata.yaml` file should state `name: mongodb-k8s` :)

2022-04-21 08:13 UTC, jnsgruk commented on README.md
> +automatic recovery on failover. The solution includes scaling and other capabilities.
Ok sure, let's leave this for now.

2022-04-21 08:22 UTC, delgod commented on CONTRIBUTING.md
> +
right, moved to charmcraft section, it uses LXD for building charms https://github.com/delgod/mongodb-k8s-operator/pull/2/commits/b73a1a992fd2669bc80941ff5959db5356ec6c60

2022-04-21 08:37 UTC, delgod commented on README.md
> +    juju deploy ./mongodb_ubuntu-20.04-amd64.charm --resource mongodb-image=mongo:4.4 --num-units=1
fixed in https://github.com/delgod/mongodb-k8s-operator/pull/2/commits/5a8f9b8ebdad7948d71b10739bc2215820fd101e

2022-04-21 08:47 UTC, delgod commented on metadata.yaml
> +    interface: mongodb-client
relation names of all charms were checked by @marceloneppel

2022-04-21 08:51 UTC, jnsgruk commented on CONTRIBUTING.md
> +
Ah yes, indeed. My mistake.

2022-04-21 08:52 UTC, jnsgruk commented on Makefile
> +redeploy:
Not sure I'd necessarily include this in the repo?

2022-04-21 08:58 UTC, jnsgruk commented on metadata.yaml
> +    interface: mongodb-client
See: https://git.launchpad.net/charm-mongodb/tree/metadata.yaml#n28

2022-04-21 10:26 UTC, delgod commented on Makefile
> +redeploy:
fixed https://github.com/delgod/mongodb-k8s-operator/pull/2/commits/359d7938b523158e9ae9015730013006592b2a96

2022-04-21 10:26 UTC, delgod commented on metadata.yaml
> +    interface: mongodb-client
added as "obsolete" interface

2022-04-21 10:29 UTC, jnsgruk approved these changes

2022-04-21 11:08 UTC, marceloneppel commented on metadata.yaml
> +    interface: mongodb-client
I made a mistake assuming the relation name in the code of this github repository as mongodb_datastore (it's only in the edge channel on charmhub; the stable version there uses mongodb as you added here). I'll confirm every of our database charms on charmhub stable channel to confirm the right relation names with what we checked before in the github repositories.

2022-04-22 06:55 UTC, MiaAltieri approved these changes

2022-04-22 07:13 UTC, merged